# Generated by Django 4.1.2 on 2022-10-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpicAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epicteammember',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
