# Generated by Django 4.1.2 on 2022-10-31 07:41

from django.db import migrations

def create_groups(apps, schema_editor):

    EpicMember = apps.get_model('EpicAPI', 'EpicTeamMember')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_member = Permission.objects.get(codename='add_epicteammember')
    change_member = Permission.objects.get(codename='change_epicteammember')
    delete_member = Permission.objects.get(codename='delete_epicteammember')
    view_member = Permission.objects.get(codename='view_epicteammember')

    add_client = Permission.objects.get(codename='add_client')
    change_client = Permission.objects.get(codename='change_client')
    delete_client = Permission.objects.get(codename='delete_client')
    view_client = Permission.objects.get(codename='view_client')

    add_contract = Permission.objects.get(codename='add_contract')
    change_contract = Permission.objects.get(codename='change_contract')
    delete_contract = Permission.objects.get(codename='delete_contract')
    view_contract = Permission.objects.get(codename='view_contract')

    add_event = Permission.objects.get(codename='add_event')
    change_event = Permission.objects.get(codename='change_event')
    delete_event = Permission.objects.get(codename='delete_event')
    view_event = Permission.objects.get(codename='view_event')

    manager_permissions = [
        add_member, change_member, delete_member, view_member, 
        add_client, change_client, delete_client, view_client, 
        add_contract, change_contract, delete_contract, view_contract, 
        add_event, change_event, delete_event, view_event
    ]

    sales_permissions = [
        add_client, add_contract, add_event,
        view_client, view_contract, view_event
    ]

    support_permissions = [
        view_client, view_contract, view_event
    ]

    manager_team = Group(name='manager_team')
    manager_team.save()
    manager_team.permissions.set(manager_permissions)

    sales_team = Group(name='sales_team')
    sales_team.save()
    sales_team.permissions.set(sales_permissions)

    support_team = Group(name='support_team')
    support_team.save()
    support_team.permissions.set(support_permissions)


    for member in EpicMember.objects.all():
        if member.role == 'MANAGER':
            # user.groups.add(user_group)
            member.groups.add(Group.objects.get(name='manager_team'))
            # manager_team.user_set.add(member)
        if member.role == 'SUPPORT':
            # support_team.user_set.add(member)
            member.groups.add(Group.objects.get(name='support_team'))
        if member.role == 'SALES':
            member.groups.add(Group.objects.get(name='sales_team'))
            # sales_team.user_set.add(member)
        else:
            member.groups.add(Group.objects.get(name='manager_team'))
            # sales_team.user_set.add(member)

class Migration(migrations.Migration):

    dependencies = [
        ('EpicAPI', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
