# Generated by Django 4.1.2 on 2022-10-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EpicAPI', '0002_epicteammember_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epicteammember',
            name='is_staff',
        ),
    ]
