# Generated by Django 4.1.2 on 2022-10-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpicAPI', '0003_auto_20221027_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epicteammember',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.FloatField(help_text='Montant du contrat en euros'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.BooleanField(help_text='True if signed, False if not signed'),
        ),
    ]
